const K="sjv2";const seed={tasks:[{id:1,t:"Finish mathematics assignment",s:"Mathematics",d:"Today",done:false},{id:2,t:"Practice Python",s:"Programming",d:"Today",done:false},{id:3,t:"Read physics chapter",s:"Physics",d:"Tomorrow",done:true}],notes:[],profile:{name:"Student",college:"My College",goal:"Build skills every day."},expenses:[],subjects:["Mathematics","Programming","Physics"]};let D=load(),sec=1500,running=false,iv;
function load(){try{return JSON.parse(localStorage.getItem(K))||structuredClone(seed)}catch{return structuredClone(seed)}}function save(){localStorage.setItem(K,JSON.stringify(D));render();toast("Saved locally")}function e(x=""){return String(x).replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]))}function toast(x){let t=document.querySelector("#toast");t.textContent=x;t.classList.add("show");setTimeout(()=>t.classList.remove("show"),1600)}
document.querySelectorAll(".nav").forEach(b=>b.onclick=()=>go(b.dataset.v));document.querySelector("#hamb").onclick=()=>document.querySelector("aside").classList.toggle("open");
function go(v){document.querySelectorAll(".nav").forEach(x=>x.classList.toggle("active",x.dataset.v===v));document.querySelectorAll(".page").forEach(x=>x.classList.remove("active"));document.getElementById(v).classList.add("active");document.getElementById("title").textContent={home:"Command Center",ai:"AI Assistant",tasks:"Tasks",study:"Study Timer",tools:"Student Tools",settings:"Settings"}[v];renderPage(v);document.querySelector("aside").classList.remove("open")}
function render(){renderPage(document.querySelector(".page.active").id);document.querySelector("#badge").textContent=D.tasks.filter(x=>!x.done).length}
function renderPage(v){if(v==="home")home();if(v==="ai")ai();if(v==="tasks")tasks();if(v==="study")study();if(v==="tools")tools();if(v==="settings")settings()}
function home(){let open=D.tasks.filter(x=>!x.done).length,done=D.tasks.length-open,spent=D.expenses.reduce((a,x)=>a+Number(x.a),0),p=D.tasks.length?Math.round(done/D.tasks.length*100):0;document.querySelector("#home").innerHTML=`<div class="grid stats"><div class="card"><div class="label">OPEN TASKS</div><div class="num">${open}</div><div class="muted">Pending actions</div></div><div class="card"><div class="label">COMPLETED</div><div class="num">${done}</div><div class="muted">Keep going</div></div><div class="card"><div class="label">PROGRESS</div><div class="num">${p}%</div><div class="muted">Task completion</div></div><div class="card"><div class="label">EXPENSES</div><div class="num">₹${spent.toFixed(0)}</div><div class="muted">Tracked locally</div></div></div><div class="grid cols" style="margin-top:16px"><div class="card"><div class="head"><h2>Today's mission</h2><button class="btn" onclick="go('tasks')">Manage</button></div>${D.tasks.filter(x=>!x.done).slice(0,4).map(row).join("")||'<div class="empty">Mission complete.</div>'}</div><div class="card"><div class="head"><h2>Focus status</h2><button class="btn primary" onclick="go('study')">Start focus</button></div><h2>${e(D.profile.goal)}</h2><div class="bar" style="margin-top:20px"><i style="width:${p}%"></i></div><p class="muted">${p}% complete</p></div></div><div class="card" style="margin-top:16px"><div class="head"><h2>Quick launch</h2></div><div class="chips"><button class="chip" onclick="go('ai')">Ask JARVIS</button><button class="chip" onclick="go('tasks')">Add task</button><button class="chip" onclick="go('tools')">CGPA calculator</button><button class="chip" onclick="go('study')">Pomodoro</button></div></div>`}
function row(x){return `<div class="row"><input class="check" type="checkbox" ${x.done?"checked":""} onchange="toggle(${x.id})"><div class="grow ${x.done?"done":""}">${e(x.t)}<div class="muted">${e(x.s)} • ${e(x.d)}</div></div><button class="btn danger" onclick="del(${x.id})">×</button></div>`}
function tasks(){document.querySelector("#tasks").innerHTML=`<div class="grid cols"><div class="card"><div class="head"><h2>Task command center</h2><button class="btn primary" onclick="addTask()">＋ Add task</button></div>${D.tasks.map(row).join("")||'<div class="empty">No tasks.</div>'}</div><div class="card"><h2>Task tips</h2><p class="muted">Break large work into a small next action. Complete it, then move to the next.</p><div class="chips"><span class="chip">25 min focus</span><span class="chip">5 min break</span><span class="chip">One task at a time</span></div></div></div>`}
function addTask(){let t=prompt("Task title");if(!t)return;let s=prompt("Subject","General")||"General";D.tasks.unshift({id:Date.now(),t,s,d:"Today",done:false});save()}function toggle(id){let x=D.tasks.find(a=>a.id===id);x.done=!x.done;save()}function del(id){D.tasks=D.tasks.filter(x=>x.id!==id);save()}
function ai(){document.querySelector("#ai").innerHTML=`<div class="grid cols"><div class="card chat"><div class="head"><h2>JARVIS AI Assistant</h2><span class="tag">DEMO MODE</span></div><div class="messages" id="msgs"><div class="msg ai"><b>JARVIS:</b> Hello ${e(D.profile.name)}. I am ready. Ask me about study planning, tasks, CGPA, or productivity.</div></div><div class="chips"><button class="chip" onclick="ask('Make me a study plan for today')">Study plan</button><button class="chip" onclick="ask('How can I study better?')">Study tips</button><button class="chip" onclick="ask('Motivate me')">Motivate me</button></div><div class="chatbar"><input class="input" id="chatin" placeholder="Ask JARVIS..." onkeydown="if(event.key==='Enter')send()"><button class="btn primary" onclick="send()">Send</button></div></div><div class="card"><h2>V2 intelligence</h2><p class="muted">This published version has a safe front-end AI interface. A real AI provider will be connected through a server-side API in the next deployment step, so your secret key never lives in the browser.</p></div></div>`}
function send(){let x=document.querySelector("#chatin").value.trim();if(x)ask(x)}function ask(x){let m=document.querySelector("#msgs");if(!m)return;let u=document.createElement("div");u.className="msg user";u.textContent=x;m.appendChild(u);let a=document.createElement("div");a.className="msg ai";let l=x.toLowerCase();let r=l.includes("motivat")?"You do not need perfect days. You need consistent days. Start with 25 focused minutes.":l.includes("plan")?"JARVIS recommends: 1) choose one important subject, 2) study 25 minutes, 3) take a 5-minute break, 4) finish one small task, 5) review before sleep.":"I can help organize your study, tasks and student workflow. Try asking for a study plan, motivation, or productivity tips.";a.innerHTML="<b>JARVIS:</b> "+r;m.appendChild(a);m.scrollTop=m.scrollHeight;document.querySelector("#chatin").value=""}
function study(){let m=String(Math.floor(sec/60)).padStart(2,"0"),s=String(sec%60).padStart(2,"0");document.querySelector("#study").innerHTML=`<div class="card timer"><div class="label">POMODORO FOCUS</div><div class="clock">${m}:${s}</div><div class="muted">25 minutes focus session</div><div class="chips" style="justify-content:center"><button class="btn primary" onclick="timerToggle()">${running?"Pause":"Start"}</button><button class="btn" onclick="resetTimer()">Reset</button></div></div>`}
function timerToggle(){if(running){clearInterval(iv);running=false}else{running=true;iv=setInterval(()=>{if(sec>0)sec--;else{clearInterval(iv);running=false;alert("JARVIS: Focus session complete.");}study()},1000)}study()}function resetTimer(){clearInterval(iv);running=false;sec=1500;study()}
function tools(){document.querySelector("#tools").innerHTML=`<div class="grid toolgrid"><div class="card tool" onclick="cgpa()"><b>Σ</b><h2>CGPA Calculator</h2><p class="muted">Calculate your semester average from grades.</p></div><div class="card tool" onclick="expense()"><b>₹</b><h2>Expense Tracker</h2><p class="muted">Quickly log a student expense.</p></div><div class="card tool" onclick="notes()"><b>✎</b><h2>Quick Notes</h2><p class="muted">Save an idea locally in your browser.</p></div></div>`}
function cgpa(){let v=prompt("Enter grade points separated by commas (e.g. 9,8,10,9)");if(!v)return;let a=v.split(",").map(Number).filter(x=>!isNaN(x));if(!a.length)return alert("Invalid values");alert("Estimated CGPA: "+(a.reduce((x,y)=>x+y,0)/a.length).toFixed(2))}
function expense(){let n=prompt("Expense name");if(!n)return;let a=Number(prompt("Amount ₹","100"));if(!a)return;D.expenses.unshift({n,a});save()}
function notes(){let n=prompt("Note title");if(!n)return;let b=prompt("Note");if(b){D.notes.unshift({n,b});save();alert("Note saved locally.")}}
function settings(){document.querySelector("#settings").innerHTML=`<div class="grid cols"><div class="card"><div class="profile"><div class="avatar">◉</div><div><h2>${e(D.profile.name)}</h2><p class="muted">${e(D.profile.college)}</p><p class="muted">Goal: ${e(D.profile.goal)}</p></div></div><hr style="border:0;border-top:1px solid #fff1;margin:20px 0"><form class="form" onsubmit="profile(event)"><input class="input" id="pn" value="${e(D.profile.name)}" placeholder="Name"><input class="input" id="pc" value="${e(D.profile.college)}" placeholder="College"><input class="input" id="pg" value="${e(D.profile.goal)}" placeholder="Goal"><button class="btn primary">Save profile</button></form></div><div class="card"><h2>Data control</h2><p class="muted">Your V2 dashboard data is stored in this browser. Export it before changing devices.</p><div class="chips"><button class="btn" onclick="backup()">Export backup</button><button class="btn danger" onclick="wipe()">Reset data</button></div></div></div>`}
function profile(ev){ev.preventDefault();D.profile={name:pn.value||"Student",college:pc.value||"",goal:pg.value||"Stay consistent."};save()}function backup(){let b=new Blob([JSON.stringify(D,null,2)],{type:"application/json"}),a=document.createElement("a");a.href=URL.createObjectURL(b);a.download="student-jarvis-backup.json";a.click()}function wipe(){if(confirm("Reset all data?")){D=structuredClone(seed);save()}}
render();
